on:
  workflow_call:
    inputs:
      runner:
        description: "The runner to use"
        required: true
        default: "ubuntu-22.04"
        type: string

permissions:
  contents: write

jobs:
  lint:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: ./.github/actions/setup-frontend

      - name: Check frontend types
        run: npm run generate && npm run build

      - name: Check frontend types
        run: npm run lint

  test:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: ./.github/actions/setup-frontend

      - name: Check frontend types
        run: npm run generate && npm run build

      - name: Test
        run: npm run test
        shell: bash

  test-install:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.13.0"

      - name: Test Installation
        run: npm install git://github.com/sciencecorp/synapse-typescript.git#${{ github.sha }}
        shell: bash

  test-install-with-token:
    runs-on: ${{ inputs.runner }}
    env:
      SCIENCE_CORPORATION_SYNAPSE_TOKEN: ${{ secrets.SCIENCECORP_SYNAPSE_READ_TOKEN }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.13.0"

      - name: Test Installation
        run: npm install git://github.com/sciencecorp/synapse-typescript.git#${{ github.sha }}
        shell: bash
